ALTER TABLE `categories`;
INSERT INTO `categories` VALUES 
(id,'Ensayo','default-picture.png'),
(id,'Novela','default-picture.png'),
(id,'Crónica','default-picture.png'),
(id,'Comic','default-picture.png'),
(id,'Cuento','default-picture.png'),
(id,'Poesía','default-picture.png'),
(id,'Magia','default-picture.png'),
(id,'Otros','default-picture.png'),
(id,'Arquitectura y diseño','default-picture.png'),
(id,'Arte','default-picture.png'),
(id,'Autoayuda y desarrollo personal','default-picture.png'),
(id,'Biografías y autobiografías','default-picture.png'),
(id,'Ciencia','default-picture.png'),
(id,'Ciencia Ficción','default-picture.png'),
(id,'Clásicos','default-picture.png'),
(id,'Cocina y gastronomía','default-picture.png'),
(id,'Deportes','default-picture.png'),
(id,'Derecho','default-picture.png'),
(id,'Economía y negocios','default-picture.png'),
(id,'Espiritualidad','default-picture.png'),
(id,'Familia, relaciones y crianza','default-picture.png'),
(id,'Feminismo','default-picture.png'),
(id,'Filosofía','default-picture.png'),
(id,'Guías prácticas','default-picture.png'),
(id,'Historia','default-picture.png'),
(id,'Humor','default-picture.png'),
(id,'Infantil','default-picture.png'),
(id,'Informática y técnica','default-picture.png'),
(id,'Jardinería','default-picture.png'),
(id,'Juvenil','default-picture.png'),
(id,'LGBT','default-picture.png'),
(id,'Matemáticas','default-picture.png'),
(id,'Medicina','default-picture.png'),
(id,'Música','default-picture.png'),
(id,'Naturaleza y animales','default-picture.png'),
(id,'No ficción','default-picture.png'),
(id,'Novela contemporánea','default-picture.png'),
(id,'Novela histórica','default-picture.png'),
(id,'Novela romántica, erótica','default-picture.png'),
(id,'Nutrición','default-picture.png'),
(id,'Policiales, thrillers y suspenso','default-picture.png'),
(id,'Política y actualidad','default-picture.png'),
(id,'Psicología','default-picture.png'),
(id,'Religion','default-picture.png'),
(id,'Teatro y películas','default-picture.png'),
(id,'Tecnología','default-picture.png'),
(id,'Textos educactivos','default-picture.png'),
(id,'Turismo','default-picture.png');


ALTER TABLE `products`;
INSERT INTO `products` VALUES 
(id,'La sangre manda','STEPHEN KING',129.00,20,'«La sangre manda». Así reza la máxima periodística que hará que Holly Gibney; la detective a la que Bill Hodges legó su agencia Finders Keepers; y uno de los personajes más queridos por los fans de Stephen King; se interese por la matanza en el instituto Albert Macready y acabe enganchada a las noticias. En esta ocasión deberá luchar contra lo que más teme...; y esta vez sola.',2,'masVendidos','sangre.jpg',5.0),
(id,'La rosa en el viento','GALLARDO SARA',850.00,10,'«La rosa que en el viento se destruye deja volar sus pétalos en una luz quemada», se lee en esta novela alucinada de Sara Gallardo, la última que publicó, un punto de llegada extraordinario para una obra deslumbrante, siempre certera, siempre singular, siempre cautivadora.',2,'masVendidos','image_2.png',5.0),
(id,'Correspondencia','OCAMPO VICTORIA & WOOLF VIRGINIA',820.00,10,'Correspondencia reúne las cartas que se escribieron V. Ocampo y V Woolf. El libro, compilado y prologado por Manuela Barral, incluye Virginia Woolf en su diario texto de Ocampo publicado por Sur en 1954 además de algunos manuscritos inéditos de ambas autoras.',3,'masVendidos','image_3.png',5.0),
(id,'Amado señor','KATCHADJIAN PABLO',690.00,30,'Tierra larga será contra la insistencia en inocular la percepción de que el camino es una línea recta y continua hacia un destino No Tan Parecidos echa por tierra esa idea y también la forma recta de la historieta',2,'ultimaVisita','image_4.png',5.0),
(id,'Tierra larga','NO TAN PARECIDOS',790.00,15,'Tierra larga será contra la insistencia en inocular la percepción de que el camino es una línea recta y continua hacia un destino? No Tan Parecidos echa por tierra esa idea y también la forma recta de la historieta',4,'recomendados','image_5.png',5.0),
(id,'Paprika Johnson y otro relatos','BARNES DJUNA',1390.00,30,'Djuna Barnes, a pesar de ser admirada por autores de la talla de James Joyce, T. S. Eliot, Carson McCullers o Anaïs Nin, cayó en el olvido al ser opacada por los hombres de su generación, «la generación perdida',5,'masVendidos','image_6.png',5.0),
(id,'It (eso)','STEPHEN KING',2399.00,10,'El libro que inspiró a la película homónima. ¿Quién o qué mutila y mata a los niños de un pequeño pueblo norteamericano? ¿Por qué llega cíclicamente el horror a Derry en forma de un payaso siniestro que va sembrando la destrucción a su paso? Esto es lo que se proponen averiguar los protagonistas de esta novela. Tras veintisiete años de tranquilidad y lejanía una antigua promesa infantil les hace volver al lugar en el que vivieron su infancia y juventud como una terrible pesadilla. Regresan a Derry para enfrentarse con su pasado y enterrar definitivamente la amenaza que los amargó durante su niñez. Saben que pueden morir; pero son conscientes de que no conocerán la paz hasta que aquella cosa sea destruida para siempre.',2,'masVendidos','it.jpg',5.0),
(id,'Acaricio Perros','ITURRASPE CONSUELO',500.00,10,'¿Cuánto tiempo hay que pisar un suelo para que se convierta en un hogar? ¿Cómo se pausa el desencuentro? . La profundidad de las preguntas que se hace la autora a lo largo de este poemario no sólo hacen de guía para esta lectura, sino que se convierten en el recurso perfecto para traducir el desconsuelo y la enorme sensación de pérdida que produce la muerte',6,'ultimaVisita','image_8.png',5.0),
(id,'El río se adelantó de golpe','PANZA ACHELI',500.00,30,'tapas en cartulina de 250 gr con impresión tipográfica a 2 tintas y tapa con Ilustración de Valeria Fukunaga materializada tipográficamente por Papel Principal mediante un cuño confeccionado mediante la técnica de clise de magnesio.',6,'recomendados','image_9.png',5.0),
(id,'Los planetas nos aman','BECHELLI ADRIÁN',1000.00,30,'Narra la historia de Miwa, una joven que decide recuperar la sabiduría olvidada de su abuelo astrólogo. Para eso, viaja a las montañas en busca de Kai, el único discípulo de su abuelo, quien la conecta con el arte de interpretar el cielo',2,'ultimaVisita','image_10.png',5.0),
(id,'Demian','HERMANN HESSE',670.00,33,'Emil Sinclair es un niño que ha pasado toda su vida en lo que él llama el Scheinwelt (mundo de ensueño o mundo de la luz), pero una mentira lo lleva a ampliar sus visiones del mundo y a conocer un personaje enigmático de nombre Max Demian que lo llevará por los senderos del autorrazonamiento destruyendo paradigmas materialistas que antes lo rodeaban.',2,'ultimaVisita','demian.jpg',5.0),
(id,'Alliances, un juego de luz','STAN LEE',1390.00,25,'¿Qué es mas real? ¿el mundo en el que nacemos o el que nos creamos? El nuevo universo del mayor creador de maravillas de nustros tiempos: Stan Lee. Una nueva generación de héroes está lista. Son jóvenes y rebeldes; poseen superpoderes extraordinarios y no tienen miedo de usarlos. ¿Su objetivo? Derrotar el mal que amenaza con destruir el planeta.',8,'masVendidos','stan-lee.jpg',5.0),
(id,'Pandemia, virus y miedo','MONICA MÜLLER',910.00,20,'Hoy el Covid-19 amenaza con su potencial letal a toda la humanidad. Para ubicarse en un escenario equidistante del terror y del escepticismo que todo lo simplifica; Mónica Müller investigó en archivos de prensa; textos médicos y testimonios directos las pandemias de 1918; 2009 y 2020; y también se propuso determinar la verosimilitud de las versiones conspirativas. En algunos casos; la conclusión es indudable. En otros; el margen de sospecha se mantiene intacto. Con el estilo del mejor thriller médico y el rigor de una especialista; Mónica Müller convierte Pandemia en un ensayo objetivo y necesario para entender lo que pasó y lo que vendrá.',8,'masVendidos','pandemia.jpg',5.0),
(id,'Un planeta llamado agua','BECHELLI ADRIÁN',1200.00,20,'Kai, maestro de astrología, viaja a la costa para reencontrarse con Miwa, su aprendiz. En un entorno natural paradisíaco, entre desencuentros y aventuras, se irá desplegando la cualidad energética de los planetas.',2,'novedades','image_14.png',5.0),
(id,'El presente','ANA BASUALDO',600.00,30,'Este libro es un recorrido por épocas, lugares y personalidades muy distintos –Leonardo Favio y Amy Winehouse, Antonio Di Benedetto y Pablo Iglesias, la quinta de San Vicente y las confiterías de Buenos Aires–, pero un hilo dorado los enhebra a todos: la mirada y el oído prodigiosos de una cronista para la que cada palabra escrita brilla con luz propia.',8,'novedades','tapa.png',5.0),
(id,'Secretos revelados','LAIN GARCIA CALVO',690.00,30,'La Biblia es mucho más que una serie de cuentos, narraciones o historias con un significado literal. La Biblia encierra un conocimiento oculto destinado solamente para los “iniciados”. Un saber que cambia la forma de pensar de todo aquél que lo descubra. Una cosa es el significado historico de la Biblia, donde se narran una serie de hechos e historias reales que ocurrieron hace muchos años atrás. Otra cosa es el significado oculto que hay detrás de esos hechos históricos, que no se expresó literalmente, pues solo unos pocos están preparados para entender y aplicar. Ese ocultismo está destinado a los iniciados que tengan el llamado de saber más y estén preparados par entenderlo.',2,'ultimaVisita','secretos.jpg',5.0),
(id,'Biss Eula','Inmunidad',1450.00,12,'Al dar a luz a su primer hijo, la ensayista Eula Biss descubre que la maternidad puede también convertirse en una experiencia aterradora y el mundo en un lugar hostil y lleno de peligros. Ante la escala inabarcable de amenazas globales como el terrorismo, los intereses de las grandes corporaciones o la contaminación medioambiental, nuestros temores y sospechas se dirigen incluso contra lo que debería protegernos: los medicamentos y las vacunas.',1,'masVendidos','image_1.png',5.0);
ALTER TABLE `products`;


ALTER TABLE `users`;
INSERT INTO `users` VALUES 
(id,'Santiago','Uría','43150555',NULL,NULL,NULL,'uriasantiago.a@gmail.com','$2b$10$R85nEPvG.NDk.IE8cIeEteTteRuFCyXDckIaM1yKJq/5WhBNB12fC','user','default-picture.png',NULL),
(id,'Noah','Goulding','26859123',NULL,NULL,NULL,'noahgoulding@gmail.com','$2b$10$.t3Ls9gip2QhAEQOqA/DOuoFbPIR3i47KC9SESz3cXtp4cdLnZhcu','user','default-picture.png',NULL),
(id,'Emilija','Chapman','24188574',NULL,NULL,NULL,'emilijachapman@gmail.com','$2b$10$db5adjx047zhkPFi/fx4COiUzGRhyrbSxO1c5CMdoXEWjCXmgeMIm','user','default-picture.png',NULL),
(id,'Lillian','Sargent','20758969',NULL,NULL,NULL,'liliansargent@gmail.com','$2b$10$DcNCmmmvmdIUbNPvdVzqY.xpoQ.OEPqWDYeLekmb47tLbOdrLGsD.','user','default-picture.png',NULL),
(id,'Donnie','Mcdonnell','33555789',NULL,NULL,NULL,'donniemcdonnell@gmail.com','$2b$10$y5yIUyXKG3j8uq3qzi8/qezgbs1aauqawCNlOfX8vgcoK4r8x.K.m','user','default-picture.png',NULL),
(id,'Waseem','Mckenzie','17859285',NULL,NULL,NULL,'waseemmckenzie@gmail.com','$2b$10$MqPCnYyaXss1KD2MJcTjIubbdYLhr/vOmTu3Ly8p1h8MCW6fz/JVu','user','default-picture.png',NULL),
(id,'Mattie','Hoffman','39687452',NULL,NULL,NULL,'mattiehoffman@gmail.com','$2b$10$64tt89btkmzWaY2os3Khle4X3NTJVWgqb1vF3CZn3ZZ906mLPJg.u','user','default-picture.png',NULL),
(id,'Christine','Craig','12333421',NULL,NULL,NULL,'christinecraig@gmail.com','$2b$10$iwDmt84rKVayEepiMRQK1eNusZ48SoXQwmcsDIMHEQpY5js7C5HYe','user','default-picture.png',NULL),
(id,'Tianna','Rowley','37195842',NULL,NULL,NULL,'tiannarowley@gmail.com','$2b$10$b5GwozvrlBnapgQf3icX/uZhBrNjmGQPlyGF51C5G8ZI8BCGljF0.','user','default-picture.png',NULL),
(id,'Inayah','Mercado','44256875',NULL,NULL,NULL,'inayahmercado@gmail.com','$2b$10$OWBOebVBmFGMYaEnoZzbC.kOmHj7klKupUo91vknfXDysaaLl2ZwS','user','default-picture.png',NULL),
(id,'Nate','Gentile', '45789654',NULL,NULL,NULL,'nategentile@gmail.com','$2b$10$iAvFw21ktNUM580TxrSOTeAgrVPIwzrTxnhdXg8mvNAp9TDsjU8N6','user','default-picture.png',NULL),
(id,'Kira','Yoshikage', '15498666',NULL,NULL,NULL,'kirayoshikage@gmail.com','$2b$10$vmk/BRrbFTVdpVC2NsRFee4VDbXwukweq559WVU9HPn8Qm3Wfn3PW','user','default-picture.png',NULL),
(id,'Smokey','Brown','22478139',NULL,NULL,NULL,'smokeybrown@gmail.com','$2b$10$q1bQePN9/T.kk.hQxULJL.VqV8bOGwbdHC7RhY6v0OGWm3DMIztea','user','default-picture.png',NULL),
(id,'Robyn','Mchamon','55716482',NULL,NULL,NULL,'robynmachamon@gmail.com','$2b$10$AyYF6dPV2peSx9qWgXtTr.kggkhOiOAKyRFrpXfnozWYENOL.Ih/O','user','default-picture.png',NULL),
(id,'Arthur','Hayes','44759351',NULL,NULL,NULL,'arthurhayes@gmail.com','$2b$10$iLgAsgTHOwYSiDIqahfjt.mJ2JIrvrelGWB/tP8JwR7VJUsDeqD2.','user','default-picture.png',NULL),
(id,'admin','admin','12345678',NULL,NULL,NULL,'admin@admin.com','$2b$10$MwprUMRD5s0MnDFuJ2ECv.JJd25BoNyJssVVOttAaqqRGM1OHjAnm','admin','default-picture.png',NULL),
(id,'visitante','visitante','87654321',NULL,NULL,NULL,'visitante@vistante.com','$2b$10$OewGhk4Dd34bLBNbUzpDXOW2psoROCiDGyv9CYYA6IxCkptDnXbh6','user','default-picture.png',NULL);
ALTER TABLE `users`;
